In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\codes\Datasets\patients_data_scored.csv")
df

,Unnamed: 0,Patient_ID,Age,Gender,BMI,Heart_Rate,Systolic_BP,Diastolic_BP,O2_Saturation,Temp,...,GCS_Score,History_Diabetes,History_Hypertension,History_Heart_Disease,Arrival_Mode,Chief_Complaint,Risk_Score,Risk_Level,Calculated_Risk_Score,Calculated_Risk_Level
0,0,sdv-id-ZEIKHc,44,F,27.6,127,137,89,88,37.6,...,15,0,1,0,Ambulance,Fever,0.97,High,0.85,High
1,1,sdv-id-cXindf,46,F,26.7,107,161,102,94,37.2,...,15,1,1,0,Ambulance,Allergy,0.66,Medium,0.65,Medium
2,2,sdv-id-OILsjH,68,F,25.4,109,145,93,87,36.8,...,14,1,1,0,Ambulance,Crash injury,0.92,High,0.99,High
3,3,sdv-id-LlLcvC,75,M,24.5,101,142,88,96,38.6,...,15,1,1,0,Walk-in,Cough and fever,0.75,High,0.30,Low
4,4,sdv-id-bfmNbx,59,O,22.3,70,138,83,95,36.2,...,15,1,1,0,Walk-in,Dizziness,0.79,High,0.20,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,sdv-id-MReans,50,F,21.5,108,150,94,97,38.2,...,12,0,0,0,Ambulance,Abdominal tenderness,0.55,Medium,0.50,Medium
9996,9996,sdv-id-lHOdCy,67,O,29.4,68,136,89,96,36.5,...,15,1,1,1,Walk-in,Chest discomfort,0.40,Medium,0.35,Low
9997,9997,sdv-id-TrokRn,23,M,23.4,112,110,77,95,36.9,...,11,0,1,0,Walk-in,Multi-trauma,0.81,High,0.60,Medium
9998,9998,sdv-id-cEWJQV,56,O,31.6,106,183,112,96,37.6,...,15,1,0,0,Walk-in,Gastric pain,0.68,Medium,0.45,Medium
9999,9999,sdv-id-eEXKyz,76,F,32.8,115,182,110,93,37.6,...,15,1,0,1,Walk-in,Chest pain,0.82,High,0.99,High

In [3]:
df.drop(columns=["Risk_Level", "Risk_Score"], inplace=True)

In [4]:
df

,Unnamed: 0,Patient_ID,Age,Gender,BMI,Heart_Rate,Systolic_BP,Diastolic_BP,O2_Saturation,Temp,Respiratory_Rate,Pain_Score,GCS_Score,History_Diabetes,History_Hypertension,History_Heart_Disease,Arrival_Mode,Chief_Complaint,Calculated_Risk_Score,Calculated_Risk_Level
0,0,sdv-id-ZEIKHc,44,F,27.6,127,137,89,88,37.6,29,3,15,0,1,0,Ambulance,Fever,0.85,High
1,1,sdv-id-cXindf,46,F,26.7,107,161,102,94,37.2,19,9,15,1,1,0,Ambulance,Allergy,0.65,Medium
2,2,sdv-id-OILsjH,68,F,25.4,109,145,93,87,36.8,24,5,14,1,1,0,Ambulance,Crash injury,0.99,High
3,3,sdv-id-LlLcvC,75,M,24.5,101,142,88,96,38.6,21,7,15,1,1,0,Walk-in,Cough and fever,0.30,Low
4,4,sdv-id-bfmNbx,59,O,22.3,70,138,83,95,36.2,15,4,15,1,1,0,Walk-in,Dizziness,0.20,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,sdv-id-MReans,50,F,21.5,108,150,94,97,38.2,16,0,12,0,0,0,Ambulance,Abdominal tenderness,0.50,Medium
9996,9996,sdv-id-lHOdCy,67,O,29.4,68,136,89,96,36.5,15,7,15,1,1,1,Walk-in,Chest discomfort,0.35,Low
9997,9997,sdv-id-TrokRn,23,M,23.4,112,110,77,95,36.9,19,9,11,0,1,0,Walk-in,Multi-trauma,0.60,Medium
9998,9998,sdv-id-cEWJQV,56,O,31.6,106,183,112,96,37.6,24,5,15,1,0,0,Walk-in,Gastric pain,0.45,Medium
9999,9999,sdv-id-eEXKyz,76,F,32.8,115,182,110,93,37.6,20,2,15,1,0,1,Walk-in,Chest pain,0.99,High

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             10000 non-null  int64
 1   Patient_ID             10000 non-null  object
 2   Age                    10000 non-null  int64
 3   Gender                 10000 non-null  object
 4   BMI                    10000 non-null  float64
 5   Heart_Rate             10000 non-null  int64
 6   Systolic_BP            10000 non-null  int64
 7   Diastolic_BP           10000 non-null  int64
 8   O2_Saturation          10000 non-null  int64
 9   Temp                   10000 non-null  float64
 10  Respiratory_Rate       10000 non-null  int64
 11  Pain_Score             10000 non-null  int64
 12  GCS_Score              10000 non-null  int64
 13  History_Diabetes       10000 non-null  int64
 14  History_Hypertension   10000 non-null  int64
 15  History_Heart_Disease  10000 non-null  int64
 16  Arrival_Mode           10000 non-null  object
 17  Chief_Complaint        10000 non-null  object
 18  Calculated_Risk_Score  10000 non-null  float64
 19  Calculated_Risk_Level  10000 non-null  object
dtypes: float64(3), int64(12), object(5)
memory usage: 1.5+ MB

In [6]:
df.describe()

,Unnamed: 0,Age,BMI,Heart_Rate,Systolic_BP,Diastolic_BP,O2_Saturation,Temp,Respiratory_Rate,Pain_Score,GCS_Score,History_Diabetes,History_Hypertension,History_Heart_Disease,Calculated_Risk_Score
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4999.50000,52.536400,26.569850,96.891700,133.329200,84.055200,94.351000,37.255910,19.163600,4.190700,14.22710,0.443700,0.555700,0.351100,0.549396
std,2886.89568,21.256996,4.003828,22.768505,26.855188,15.593565,3.566941,0.659324,4.449271,2.450946,1.51834,0.496845,0.496913,0.477338,0.290729
min,0.00000,19.000000,19.500000,54.000000,80.000000,48.000000,85.000000,35.900000,14.000000,0.000000,9.00000,0.000000,0.000000,0.000000,0.100000
25%,2499.75000,34.000000,23.300000,79.000000,112.000000,73.000000,92.000000,36.800000,15.000000,2.000000,14.00000,0.000000,0.000000,0.000000,0.300000
50%,4999.50000,51.000000,26.300000,95.000000,133.000000,85.000000,95.000000,37.200000,18.000000,4.000000,15.00000,0.000000,1.000000,0.000000,0.550000
75%,7499.25000,70.000000,29.600000,114.000000,155.000000,96.000000,97.000000,37.700000,22.000000,6.000000,15.00000,1.000000,1.000000,1.000000,0.800000
max,9999.00000,94.000000,36.200000,150.000000,190.000000,115.000000,100.000000,39.200000,32.000000,9.000000,15.00000,1.000000,1.000000,1.000000,0.990000

In [7]:
df.rename(columns={"Calculated_Risk_Score": "Risk_Score", "Calculated_Risk_Level": "Risk_Level"}, inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             10000 non-null  int64
 1   Patient_ID             10000 non-null  object
 2   Age                    10000 non-null  int64
 3   Gender                 10000 non-null  object
 4   BMI                    10000 non-null  float64
 5   Heart_Rate             10000 non-null  int64
 6   Systolic_BP            10000 non-null  int64
 7   Diastolic_BP           10000 non-null  int64
 8   O2_Saturation          10000 non-null  int64
 9   Temp                   10000 non-null  float64
 10  Respiratory_Rate       10000 non-null  int64
 11  Pain_Score             10000 non-null  int64
 12  GCS_Score              10000 non-null  int64
 13  History_Diabetes       10000 non-null  int64
 14  History_Hypertension   10000 non-null  int64
 15  History_Heart_Disease  10000 non-null  int64
 16  Arrival_Mode           10000 non-null  object
 17  Chief_Complaint        10000 non-null  object
 18  Risk_Score             10000 non-null  float64
 19  Risk_Level             10000 non-null  object
dtypes: float64(3), int64(12), object(5)
memory usage: 1.5+ MB

In [9]:
df.to_csv(r"D:\codes\Datasets\patients_data_scored.csv", index=False)